server:
  port: 3000
application:
  domain: juice-sh.op
  name: 'Senacor Juice Shop'
  logo: JuiceShopCTF_Logo.png
  favicon: favicon_ctf.ico
  numberOfRandomFakeUsers: 0
  showChallengeSolvedNotifications: true
  showChallengeHints: false
  showVersionNumber: false
  theme: spacelab # Options: cerulean  cosmo  cyborg  darkly  flatly lumen  paper  readable  sandstone  simplex  slate  spacelab  superhero  united  yeti
  gitHubRibbon: none # Options: darkblue  gray  green  orange  red  white  none
  twitterUrl: 'https://twitter.com/senacor'
  facebookUrl: 'https://www.facebook.com/Senacor'
  planetOverlayMap: orangemap2k.jpg
  planetName: Saftopia
  recyclePage:
    topProductImage: fruit_press.jpg
    bottomProductImage: apple_pressings.jpg
  altcoinName: Juicycoin
  cookieConsent:
    backgroundColor: '#eb6c44'
    textColor: '#ffffff'
    buttonColor: '#f5d948'
    buttonTextColor: '#000000'
    message: 'This website uses fruit cookies to ensure you get the juiciest tracking experience.'
    dismissText: 'Me want it!'
    linkText: 'But me wait!'
    linkUrl: 'https://www.youtube.com/watch?v=9PnbKL3wuH4'
  securityTxt:
    contact: 'mailto:donotreply@Senacor-juice.shop'
    encryption: 'https://keybase.io/bkimminich/pgp_keys.asc?fingerprint=19c01cb7157e4645e9e2c863062a85a8cbfbdcda'
    acknowledgements: '/#/score-board'
products:
  -
    name: 'Apple Juice (1000ml)'
    price: 1.99
    description: 'The all-time classic.'
    image: apple_juice.jpg
    reviews: # Options 'author': admin, jim, bender, ciso, support, morty, mc.safesearch
      - { text: 'One of my favorites!', author: admin }
  -
    name: 'Orange Juice (1000ml)'
    description: 'Made from oranges hand-picked by Uncle Dittmeyer.'
    price: 2.99
    image: orange_juice.jpg
  -
    name: 'Eggfruit Juice (500ml)'
    description: 'Now with even more exotic flavour.'
    price: 8.99
    image: eggfruit_juice.jpg
    reviews:
      - { text: 'I bought it, would buy again. 5/7', author: admin }
  -
    name: 'Raspberry Juice (1000ml)'
    description: 'Made from blended Raspberry Pi, water and sugar.'
    price: 4.99
    image: raspberry_juice.jpg
  -
    name: 'Lemon Juice (500ml)'
    description: 'Sour but full of vitamins.'
    price: 2.99
    image: lemon_juice.jpg
  -
    name: 'Banana Juice (1000ml)'
    description: 'Monkeys love it the most.'
    price: 1.99
    image: banana_juice.jpg
    reviews:
      - { text: 'Fry liked it too.', author: bender }
  -
    name: 'Senacor Juice Shop T-Shirt'
    description: 'Real fans wear it 24/7!'
    price: 22.49
    image: fan_shirt.jpg
  -
    name: 'Senacor Juice Shop CTF Girlie-Shirt'
    description: 'For serious Capture-the-Flag heroines only!'
    price: 22.49
    image: fan_girlie.jpg
  -
    name: 'Senacor SSL Advanced Forensic Tool (O-Saft)'
    description: 'O-Saft is an easy to use tool to show information about SSL certificate and tests the SSL connection according given list of ciphers and various SSL configurations.'
    price: 0.01
    image: orange_juice.jpg
    urlForProductTamperingChallenge: 'https://www.Senacor.com/index.php/O-Saft'
  -
    name: 'Christmas Super-Surprise-Box (2014 Edition)'
    description: 'Contains a random selection of 10 bottles (each 500ml) of our tastiest juices and an extra fan shirt for an unbeatable price!'
    price: 29.99
    image: undefined.jpg
    useForChristmasSpecialChallenge: true
  -
    name: 'Senacor Juice Shop-CTF Velcro Patch'
    description: '4x3.5" embroidered patch with velcro backside. The ultimate decal for every tactical bag or backpack!'
    price: 2.92
    image: velcro-patch.jpg
    reviews:
      - { text: 'This thang would look phat on Bobby''s jacked fur coat!', author: mc.safesearch }
      - { text: 'Looks so much better on my uniform than the boring Starfleet symbol.', author: jim }
  -
    name: 'Green Smoothie'
    description: 'Looks poisonous but is actually very good for your health! Made from green cabbage, spinach, kiwi and grass.'
    price: 1.99
    image: green_smoothie.jpg
    reviews:
      - { text: 'Fresh out of a replicator.', author: jim }
  -
    name: 'Quince Juice (1000ml)'
    description: 'Juice of the <em>Cydonia oblonga</em> fruit. Not exactly sweet but rich in Vitamin C.'
    price: 4.99
    image: quince.jpg
  -
    name: 'Apple Pomace'
    description: 'Finest pressings of apples. Allergy disclaimer: Might contain traces of worms. Can be <a href="/#recycle">sent back to us</a> for recycling.'
    price: 0.89
    image: apple_pressings.jpg
  -
    name: 'Fruit Press'
    description: 'Fruits go in. Juice comes out. Pomace you can send back to us for recycling purposes.'
    price: 89.99
    image: fruit_press.jpg
  -
    name: 'Senacor Juice Shop Logo (3D-printed)'
    description: 'This rare item was designed and handcrafted in Sweden. This is why it is so incredibly expensive despite its complete lack of purpose.'
    price: 99.99
    image: 3d_keychain.jpg # Exif metadata contains "OpenSCAD" as subtle hint...
    fileForRetrieveBlueprintChallenge: JuiceShop.stl # ...to blueprint file type
  -
    name: 'Carrot Juice (1000ml)'
    description: 'As the old German saying goes: "Carrots are good for the eyes. Or has anyone ever seen a rabbit with glasses?"'
    price: 2.99
    image: carrot_juice.jpeg
ctf:
  countryMapping: ~
  showFlagsInNotifications: true
  showCountryDetailsInNotifications: none # Options: none  name  flag  both
  